# Generated by Django 4.1.5 on 2023-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilitie', models.CharField(max_length=50, verbose_name='abilitie')),
            ],
            options={
                'verbose_name': 'abilitie',
                'verbose_name_plural': 'abilities',
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name')},
        ),
    ]
