# Generated by Django 4.1.5 on 2023-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_abilitie_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='abilities',
            field=models.ManyToManyField(to='empleados.abilitie'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='empleado'),
        ),
    ]
